### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by Panquesito7** [Snailedlt/GameLogger#1]
See https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/ for more information.
I recommend adding the [MIT license](https://mit-license.org), which is one of the simplest and best open-source licenses.

**Comment by Snailedlt** [comment]
It's a dead school project which doesn't work anymore, so we'll probably just keep it the way it is, but thanks anyways :)
